### ISSUE TITLE
Problem with installation process on Windows 7

### ISSUE THREAD

**Issue by andrear4568** [ladybug-analysis-tools/butterfly#162] opened 2017-01-10 18:18 UTC
Hello Mostapha,

I have problems to install Butterfly on my pc with Win7.
There it is the installation process I do:

PART 1: NEW INSTALLED SOFTWARES
1. OF_Env_Create (run as admin)
2. OpenFOAM_Start (run as admin)
3. Open Oracle VM and start the default machine
4. Open Kinematic (Alpha)--> Error: connect ENONENT//./pipe/docker_engine as follow
![aa](https://cloud.githubusercontent.com/assets/25038491/21818491/fae5d9f8-d75f-11e6-97a4-b0c1f8f6745a.PNG)
Both the options  (Retry setup and Use Virtual Box) give me error as well.

5. Open Docker Quickstart and I have this issue (see image below)
![bb](https://cloud.githubusercontent.com/assets/25038491/21818568/3f865ce0-d760-11e6-8597-2b4cd2974195.PNG)

PART2: RHINO + GH
1. Open Rhino as admin
2. Install the plugin with the installation file.gh
3. Run indoor airflow sample file.gh
4. When I run 2.1 Blockmesh I have this error (see image below)
![cc](https://cloud.githubusercontent.com/assets/25038491/21818698/b8c3f2c0-d760-11e6-9855-d9d0295459c0.PNG)

I am stuck at this point, and I do not how to proceed forward.

I thank you in advance.

Andrea

**Comment by mimarilker** [comment] 2017-01-11 18:13
Follow the instructions in the attached link and let us know if it works. Actually these inst. are for win10 but it should work for win7 too.

https://github.com/ladybug-analysis-tools/butterfly/wiki/Windows-10-Installation-Notes

**Comment by mostaphaRoudsari** [comment] 2017-01-11 23:01
@andrear4568 as @mimarilker said you need to make sure every step of the installation has been successful otherwise you won't be able to run OpenFOAM.

In your case the docker is not installed correctly and it's normal that the rest is not working. Did you follow the installation instruction including the changes in BIOS?

**Comment by andrear4568** [comment] 2017-01-12 12:08
Hello guys, thanks for your answer.

I have followed, the Windows 10 installation notes and Butterfly started finally to work.

Just for you to know, during the scripting process in Docker (second step from the guide https://github.com/ladybug-analysis-tools/butterfly/wiki/Windows-10-Installation-Notes), I have a little issue:

_This is the step:
“press enter,then write:
docker load -i of_v1612plus_centos66.tar”_

You can see the message from the image "The system cannot find the file specified"
![rrr](https://cloud.githubusercontent.com/assets/25038491/21889141/558ce526-d8bf-11e6-9d65-2a5132925369.PNG)

It looks like it is not influencing the GH definition.

Thanks you guys for your assistance

Andrea

**Comment by mimarilker** [comment] 2017-01-12 12:10
Because you are not at the true directory, as you see the current directory is "c". So, please review the instructions again and write the correct path.

**Comment by andrear4568** [comment] 2017-01-12 12:42
Hello @mimarilker 
you're right I've wrong to type the code.
Now it is working perfectly
![qqq](https://cloud.githubusercontent.com/assets/25038491/21890194/73f9f7c4-d8c4-11e6-8f6d-c850d3c5c8b0.PNG)

thanks

**Comment by mimarilker** [comment] 2017-01-12 13:00
good to hear!

**Comment by andrear4568** [comment] 2017-01-13 10:22
Luckily the are some people that can illuminate some users with problems !

Thank you for you help

**Comment by andrear4568** [comment] 2017-01-13 11:12
@mimarilker First of all thank you for your help, I really apreciate it.
Please consider that not all users are at the same level, and it is possible that sometimes someone might ask some questions, that you consider irrelevant. 
However - as you previously wrote - there was an error on the guide instructions, so, I don't see any "problematic" situation after that.
ps: please do not edit your replies, otherwise, the conversation meaning might change  :)

**Comment by mimarilker** [comment] 2017-01-13 11:17
Yes, you are right, however the problem was with github's text file format, not with me and you:)

**Comment by andrear4568** [comment] 2017-01-13 11:22
Thanks for saying it, I appreciate it.
Good luck, and thanks again for you fantastic work!

**Comment by mostaphaRoudsari** [comment] 2017-01-14 00:10
I'll close this one as the issue is already solved!

**Closed by mostaphaRoudsari** 2017-01-14 00:10 UTC
Labels: question

**Comment by aorukaya** [comment] 2017-12-29 02:54
Hello everyone, 

I read this thread and I am having the same problem but am unable to solve it using the solutions mentioned. I followed everything. Below is some screenshots of what's happening. 

![2](https://user-images.githubusercontent.com/34929393/34428330-87599cb2-ec86-11e7-9209-bacada172406.PNG)
![1](https://user-images.githubusercontent.com/34929393/34428331-878516ee-ec86-11e7-9c06-575d9fbe9abe.PNG)

any help would be appreciated! thanks
