### ISSUE TITLE
Issue with creating mesh, 'Could not find file...'

### ISSUE THREAD

**Issue by MeloGG** [ladybug-analysis-tools/butterfly#176] opened 2017-02-07 12:15 UTC
Hi All,

I have just started using butterfly and struggling to go ahead with the example file "outdoor_airflow".
I tried to see if someone had the same problem but I could not find any post on it. Please direct me there if there is one.
I have a problem when running blockmesh and snappyhexmesh. I have attached a screenshot that hopefully can help in understanding the problem. It looks like butterfly is not able to find/create files.
This is similar to the problem I had when I started using ladybug and honeybee and I solved it simply changing the default folder in which ladybug and honeybee where saving/creating the files (I changed it to C:\ladybug and C:\honeybee). However, I could not manage to do the same in butterfly and of course I am not sure whether it is exactly the same issue. The virtual box seems to work fine (please see attached).
The grasshopper script is exactly the same as the example one.
Does anyone have any ideas on how to solve this?

Many thanks in advance for your help and for developing these amazing tools!

![butterfly-problem mesh](https://cloud.githubusercontent.com/assets/25609851/22690504/07bd344e-ed2e-11e6-9edc-771777205173.PNG)

![virtualbox](https://cloud.githubusercontent.com/assets/25609851/22690201/814b7e44-ed2c-11e6-8b01-2710b5a9732e.PNG)

![butterfly-problem mesh_2](https://cloud.githubusercontent.com/assets/25609851/22690724/14c40ba8-ed2f-11e6-8061-27be655da54a.PNG)

**Comment by MikkiSeidenschnur** [comment] 2017-02-07 13:21
Hello @MeloGG 
1. Are you running Rhinoceros as an admin?  
2. Are you using windows 7 or 10? I don't think win 7 has especially good compatibility with Butterfly. based on #162. 
3. If windows 10 - Did you follow the instructions on [https://github.com/ladybug-analysis-tools/butterfly/wiki/Windows-10-Installation-Notes](url)?
4. Did you check that the Rhino template is in meters? If it's not in meters you should change it.
5. Do you have Virtualization turned on in the BIOS of the computer?
6. I don't see the username folder. Just to mention it - It should not contain whitespaces for instance "Mikki Seidenschnur". As far as I know, Linux doesn't deal well with whitespaces. 

Just the few things that I can think of, keep us updated and let's get this working for you as well,

Best regards
Mikki Seidenschnur

**Comment by mostaphaRoudsari** [comment] 2017-02-07 13:42
I second @MikkiSeidenschnur's comments. Is there a white space in the username? I assume that's why you had to change the path also for ladybug and honeybee.

**Comment by MeloGG** [comment] 2017-02-07 23:28
Hi Mikki and Mostapha,

Thank you for your feedback. Answering to the questions:

1) Yes, I am running Rhino as admin.

2) I am using windows 7. I will check that post well and see if it can help. I have attached a screenshot of the Docker Quickstart terminal. It looks like something is missing?

3) See above, my understanding from what you are saying is that those notes for windows 10 may actually help also windows 7 users.

4) I created a Rhino file in meters for large objects, so that should be fine.

5) Virtualization should be turned on, please see the screenshot attached.

6) I have attached the screenshot and you should be able to see the username. I think there is no issue with that? Ladybug and honeybee were failing in creating the folders/files in the user folder  standard path (despite I had admin privileges) and providing a different folder was solving the problem (unless you confirm that the problem is the username).

Hopefully my answers may help in finding the issue.


![virtualization_enabled](https://cloud.githubusercontent.com/assets/25609851/22716208/bd156aa6-ed8c-11e6-9de6-ad9f652486c6.PNG)
![docker quickstart terminal](https://cloud.githubusercontent.com/assets/25609851/22716212/c003acd2-ed8c-11e6-8cb6-00165cf65eae.PNG)
![username](https://cloud.githubusercontent.com/assets/25609851/22716217/c7b1e124-ed8c-11e6-81d3-96e41f7159dc.PNG)

Regards

**Comment by mostaphaRoudsari** [comment] 2017-02-07 23:38
@MeloGG is the butterfly folder created under c:\users\Carmelo.eoc? I'm not sure if that `.` is what making the issue.
In case the folder is already created run the OpenFOAM_Start batch file as an administrator. and type comments below and see if every thing works fine

```bash
cd workingDir/butterfly/outdoor_airflow
ls
blockMesh
```

![image](https://cloud.githubusercontent.com/assets/2915573/22716571/929fc78a-ed64-11e6-8c0a-1df792e58d40.png)

**Comment by MeloGG** [comment] 2017-02-08 18:21
Hi Mostapha,

Thanks for your help. I may have understood what is happening here. I followed the steps you said. Weirdly, on the machine there are two user folders for the same user. One called Carmelo and one Carmelo.eoc. It seems that OpenFoam is using as WorkingDir the folder called Carmelo while butterfly is creating the butterfly folder in Carmelo.eoc. I tried to copy the folder in the WorkingDir and the mesh is created correctly (I can visualise it in Rhino). It could be that the **`.`** in the username is effectively creating the problem and that is why Openfoam is using the other folder (Carmelo). This could also explain why I have to use different folders with ladybug and honeybee. I hope this is not confusing. I am trying to fix the issue of the "double" user folder with the IT and then I will let you know if everything works fine.
I am attaching the screen shot anyway.

I have two other questions related to this topic:
- I have installed the version 1606 of OpenFOAM, is it better to install the 1612? I thought butterfly was not compatible yet with this.
- Finally, when we download OpenFOAM, we have three files but it seems we only use the executable file for the installation. What are the other files used for?

Thanks

![openfoam](https://cloud.githubusercontent.com/assets/25609851/22751053/f484d8ca-ee2a-11e6-82ca-94d76261fc27.PNG)

**Comment by mostaphaRoudsari** [comment] 2017-02-09 01:19
Hi Carmelo,
At least now we know what the issue is. Butterfly and OpenFOAM are not looking to the same folder. There is a solution to solve this by using `docker inspect` command instead of our current approach. We can also give the option to user to overwrite the username. Each has their own limitations.

Back to your questions:
1. Yes. You can use the latest version of OpenFOAM and it should work fine.
2. Not sure which files are you talking about. It's only an installer file.

**Comment by MeloGG** [comment] 2017-02-09 12:23
Hi Mostapha,

It looks like modifying the user folder is not an easy thing as I would have to delete it and create it from scratch which I am not very keen to do.
Could you please explain more how to use the other two options? Do you think the problem is definitely caused by the `.` in the user folder? If there would be a way of changing the folder used by butterfly similarly to what is done in ladybug/honeybee it could be possible to match it with the one used by OpenFoam and that should work too?

In regards to my question about the files, please see the image below. are not files for windows? In the installation guide is written to download all of them.

Thanks again for the help.

![files_openfoam](https://cloud.githubusercontent.com/assets/25609851/22782999/b6255e32-eec1-11e6-80bf-8e2bd81f66aa.PNG)

![installation procedure](https://cloud.githubusercontent.com/assets/25609851/22783150/7a8fcad2-eec2-11e6-9bef-15c4fbc3b822.PNG)

**Comment by MikkiSeidenschnur** [comment] 2017-02-09 12:29
@MeloGG As far as I know you should only download the "Installer.exe" which is a package that installs everything that you need to run it on windows. At least I got it working by only downloading the executable and running it. 

/Mikki

**Comment by DambronOlivier** [comment] 2017-02-09 12:49
@MeloGG,

All is successful when installing Openfoam1606. And then upgrading to v1612 worked for me. 
However cleaning everything and installing v1612 directly caused many issues on two computer that I tested.

If you anyone could confirm this perhaps we could edit the wiki. @mostaphaRoudsari, would you have an idea on this issue?

**Comment by MikkiSeidenschnur** [comment] 2017-02-09 12:52
@DambronOliver

I actually first had a working version of 1606, uninstalled it, and then installed the 1612. It's working ok for me now, except from this one issue with SolutionParams #178

**Comment by DambronOlivier** [comment] 2017-02-09 13:00
@MikkiSeidenschnur

The issues I encountered were after uninstalling docker toolbox, oracle VM , openfoam 1606. Reinstalling directly 1612 caused many docker issues.

**Comment by MikkiSeidenschnur** [comment] 2017-02-09 13:24
@DambronOlivier 

Yes, I'm sorry if you misunderstood me, but that was also what I did - I uninstalled everything, incl. Docker, VM, and OF. And then I installed everything again with v1612 and Docker etc.

**Comment by mostaphaRoudsari** [comment] 2017-02-09 15:05
1. I just fixed the installation instructions. You only need to download the installer. The other two are source code.
2. I have never had any of these issues. I installed OpenFOAM 3 times on two different laptops and just by following the directions everything has worked fine for me so I don't really have that much input on installation issues.
3. Butterfly uses `os.path.expanduser('~')` to find the path to user folder and [then creates a butterfly folder inside that folder](https://github.com/ladybug-analysis-tools/butterfly/blob/master/butterfly/case.py#L82). You can actually overwrite this by setting up `case.workingDir` before saving the case. Unlike ladybug and honeybee we can't change the folder and we have to follow the shared folder that OpenFOAM picks up on Windows. In your case try to insert a python component like the image below between creating the case and the meshing. This will update the working directory and save the files in the right location.

![image](https://cloud.githubusercontent.com/assets/2915573/22788777/e5c90886-eeae-11e6-9347-7481b2e5d1f9.png)

If this solves the issue then we can make a component or add a file to installation that let's you set up the path to some folder other than the default folder.

**Comment by MeloGG** [comment] 2017-02-09 22:20
Hi Mostapha,

I managed to run the analysis and it looks like is working fine. Thanks a lot for your help; is there any other application/occasion in which I may need to change the working folder?
Hopefully I will not have this issue anymore.  

Regards

**Comment by mostaphaRoudsari** [comment] 2017-02-09 22:35
Hi @MeloGG, Great! We can close this for now.
You only need to do this once you create the case and before running any of the OpenFOAM commands. It means you should insert this component after `Create Case from Geometry` and `Create Case from Tunnel` components.

**Closed by mostaphaRoudsari** 2017-02-09 22:35 UTC
Labels: enhancement, question
